---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Creates S3 bucket and set a required bucket policy for GameAnalytics data
  export to write the data to the bucket

Parameters:
  S3PolicyStackTemplateURL:
    Type: String
    Description: URL of the CFN template to provision an access point
  GameAnalyticsExportRoleArn:
    Type: String
    Default: arn:aws:iam::118928031713:role/live-export-job-batch-copy-role
    Description: ARN of the role assumed by the GameAnalytics export service

Resources:
  S3PolicyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref S3PolicyStackTemplateURL
      Parameters:
        BucketName: !Ref S3Bucket
        GameAnalyticsExportRoleArn: !Ref GameAnalyticsExportRoleArn
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: true
          RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !GetAtt S3BucketKey.Arn
              SSEAlgorithm: aws:kms
  S3BucketKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Used to encrypt GameAnalytics export data
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: allow-ga-write
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow GameAnalytics to write the data
            Effect: Allow
            Principal:
              AWS: !Ref GameAnalyticsExportRoleArn
            Action:
              - 'kms:GenerateDataKey'
            Resource: '*'

Outputs:
  BucketARN:
    Value: !GetAtt S3Bucket.Arn
    Description: ARN of the bucket where the data will be exported to
